version: '3'
services:
    redis:
        image: redis:latest

    dash_trace_v3_redis:
        image: 979711578039.dkr.ecr.us-east-2.amazonaws.com/dash_trace_v3_redis:latest
        depends_on: 
            - redis
        ports: 
            - 8051:8050